---
title: Hackeandosuaviagem
timezone: America/Sao_Paulo
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
serve: true
exclude:
- Gemfile
- Gemfile.lock
- README.textile
permalink: "/posts/:title"
paginate: 5
paginate_path: blog/page/:num
markdown: kramdown
url: http://viagem.ianborges.coach
excerpt_separator: "<!--more-->"
gems:
- jekyll-paginate
- jekyll-sitemap
